version: '3'

services:
  redis:
    image: 'redis:3.2-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    build: . #'.' specifies Current directory
    depends_on: #It specifies web depends on redis and run redis before web each time we run
      - 'redis'
    env_file:
      - '.env'
    #image: 'nawinkumar94/web:1.0' #tags the image with my docker account during build
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'

volumes:
  redis: {}
